### ISSUE TITLE
Add PKGBUILD for qt5-graphicaleffects-git from the AUR

### ISSUE THREAD

**Issue by iBelieve** [papyros/powerpack#3]
Needed for qml-material

**Comment by githubgeeker** [comment]
ok, I try this solution. I will keep you updated.
Thank you!!

**Comment by githubgeeker** [comment]
Great! Thank you so much,everything works fine now!
I have successfully built a gnome.dvi file but don't works in virtual box 😔😔
Damn!
By the way, papyrOs is a great job and I can't wait for try it.
Thanks again man!

**Comment by iBelieve** [comment]
We no longer use this repository, so I'm closing the issue.
