### ISSUE TITLE
'gsettings-qt-bzr' missing dependency?

### ISSUE THREAD

**Issue by mmetak** [papyros/powerpack#7]
Hi. I was building Papyros packages in OBS and it failed to build without 'qt5-declarative-git'.
Anyway, here is my OBS papyros project page/repo for Arch linux.

https://build.opensuse.org/project/show/home:metakcahura:arch-papyros

**Comment by iBelieve** [comment]
Could you comment on the AUR package [here](https://aur.archlinux.org/packages/gsettings-qt-bzr)? Once that's updated, we'll just pull in the new version.

**Comment by mmetak** [comment]
Done.

**Comment by ricardomv** [comment]
i think this is fixed

**Comment by iBelieve** [comment]
Updated to the latest AUR PKGBUILD, which fixes this bug.
